extends GutTest
## CapnTool: the in-process codegen path (resolve capnp -> `capnp compile -o-`
## -> CapnCodegen, no CLI shim, no headless-Godot subprocess). Needs a real
## capnp binary, so it is gated on CAPNGODO_TEST_CAPNP (or capnp on PATH) and
## skips cleanly when absent — same external-tool posture as the interop suite.
## Run locally with:
##   CAPNGODO_TEST_CAPNP=/path/to/capnp CAPNGODO_GODOT=... sh tools/run_tests.sh

const OUT_DIR: String = "user://capngodo_test_gen"


func _capnp() -> String:
	var env: String = OS.get_environment("CAPNGODO_TEST_CAPNP")
	if not env.is_empty() and FileAccess.file_exists(env):
		return env
	return CapnTool.resolve_capnp()


func _read_text(path: String) -> String:
	var f: FileAccess = FileAccess.open(path, FileAccess.READ)
	if f == null:
		return ""
	var s: String = f.get_as_text()
	f.close()
	return s


func test_compile_to_cgr_parses() -> void:
	var capnp: String = _capnp()
	if capnp.is_empty():
		pass_test("capnp not available (set CAPNGODO_TEST_CAPNP); skipping")
		return
	var schema: String = ProjectSettings.globalize_path("res://tests/golden/defaults.capnp")
	var cgr: PackedByteArray = CapnTool.compile_to_cgr(capnp, schema)
	assert_false(cgr.is_empty(), "capnp dumped CGR bytes")
	var root: CapnReader.StructReader = CapnSchema.open_request(cgr)
	assert_not_null(root, "CGR parses as a CodeGeneratorRequest")


func test_generate_to_dir_matches_cli_golden() -> void:
	# The in-process path must produce byte-identical output to the committed
	# golden (which was generated by the CLI shim) — proving the two codegen
	# entry points agree.
	var capnp: String = _capnp()
	if capnp.is_empty():
		pass_test("capnp not available (set CAPNGODO_TEST_CAPNP); skipping")
		return
	var schema: String = ProjectSettings.globalize_path("res://tests/golden/defaults.capnp")
	var result: CapnTool.Result = CapnTool.generate_to_dir(capnp, schema, OUT_DIR)
	assert_true(result.ok, "generation succeeded: %s" % result.error)
	assert_eq(result.written.size(), 1, "one .gd written")
	if result.written.is_empty():
		return
	assert_true(result.written[0].ends_with("defaults.capnp.gd"), "named by schema basename")
	var generated: String = _read_text(result.written[0])
	var golden: String = _read_text("res://tests/generated/defaults.capnp.gd")
	assert_eq(generated, golden, "in-process output matches the CLI-generated golden")
